"""empty message

Revision ID: 60f1f9a5191f
Revises: 793b28a93f16
Create Date: 2023-09-02 10:36:50.381857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60f1f9a5191f'
down_revision = '793b28a93f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
